name = "ClassicASP"
grammar = "classicasp"
path_suffixes = ["asp", "asa", "aspx", "ascx"]
first_line_pattern = '^#!.*asp'
line_comments = ["'"]
documentation = { start = "''", end = "''", prefix = "* ", tab_size = 1 }
autoclose_before = ";:.,=}])>"
brackets = [
    { start = "{", end = "}", close = true, newline = true },
    { start = "[", end = "]", close = true, newline = true },
    { start = "(", end = ")", close = true, newline = true },
    { start = "\"", end = "\"", close = true, newline = false, not_in = ["string"] },
    { start = "'", end = "'", close = true, newline = false, not_in = ["string"] },
    { start = "/*", end = " */", close = true, newline = false, not_in = ["comment", "string"] },
]
